# Generated by Django 3.2.16 on 2024-09-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('title_selector', models.CharField(max_length=250)),
                ('description_selector', models.CharField(max_length=250)),
                ('key_words_selector', models.CharField(default="meta[property*='og:title']", max_length=250)),
                ('img_selector', models.CharField(max_length=250)),
                ('price_selector', models.CharField(max_length=250)),
                ('discount_selector', models.CharField(max_length=250)),
                ('is_stuck', models.BooleanField(default=False)),
                ('stuck_selector', models.CharField(max_length=250)),
                ('is_feature', models.BooleanField(default=False)),
                ('features_selector', models.CharField(max_length=250)),
            ],
        ),
    ]
