# Generated by Django 3.2.16 on 2024-09-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='pagination_path',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='websites',
            name='product_selector',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='websites',
            name='description_selector',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='websites',
            name='discount_selector',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='websites',
            name='features_selector',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='websites',
            name='img_selector',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='websites',
            name='is_feature',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='websites',
            name='is_stuck',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='websites',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='websites',
            name='price_selector',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='websites',
            name='stuck_selector',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='websites',
            name='title_selector',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
