# Generated by Django 3.2.16 on 2024-09-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_websites_export_out_of_stuck'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='img_click',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
