# Generated by Django 3.2.16 on 2024-09-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_websites_img_click'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websites',
            name='stuck_attr',
        ),
        migrations.AlterField(
            model_name='websites',
            name='img_attr',
            field=models.CharField(blank=True, default='src', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='websites',
            name='main_img_attr',
            field=models.CharField(blank=True, default='src', max_length=250, null=True),
        ),
    ]
