# Generated by Django 3.2.16 on 2024-09-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20240923_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='second_price_attr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='websites',
            name='second_price_selector',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
