# Generated by Django 3.2.16 on 2024-09-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20240923_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='websites',
            old_name='features_attr',
            new_name='features_key_attr',
        ),
        migrations.AddField(
            model_name='websites',
            name='features_key_selector',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='websites',
            name='features_value_attr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='websites',
            name='features_value_selector',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
