# Generated by Django 3.2.16 on 2024-09-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20240923_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='number_of_products',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
