# Generated by Django 3.2.16 on 2024-09-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_websites_number_of_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='product_click',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
