# Generated by Django 3.2.16 on 2024-10-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_websites_product_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='static_price',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='websites',
            name='title_prefix',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
