# Generated by Django 4.2.9 on 2024-10-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_websites_inside_category_selector'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='ar_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='websites',
            name='en_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
