# Generated by Django 4.2.9 on 2024-10-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_websites_ar_link_websites_en_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='pagination_click',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
