# Generated by Django 4.2.9 on 2024-10-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_websites_pagination_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='ar_selector',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
