# Generated by Django 4.2.9 on 2024-10-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='api_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
