# Generated by Django 4.2.9 on 2024-10-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_blogs_api_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='ar_attr',
            field=models.CharField(blank=True, default='href', max_length=250, null=True),
        ),
    ]
