# Generated by Django 4.2.9 on 2024-10-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_websites_ar_attr'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='is_price_have_comma',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
