# Generated by Django 4.2.9 on 2024-10-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_websites_is_price_have_comma'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='change_content',
            field=models.BooleanField(default=True),
        ),
    ]
