# Generated by Django 4.2.9 on 2024-12-09 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_websites_inner_selector_websites_not_contains_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
