# Generated by Django 4.2.9 on 2024-12-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_websites_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websites',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
