# Generated by Django 4.2.9 on 2024-12-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_websites_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websites',
            name='created_at',
        ),
    ]
