# Generated by Django 4.2.9 on 2024-12-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_websites_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='ar_title_prefix',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
