# Generated by Django 4.2.9 on 2024-12-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_websites_ar_title_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='websites',
            name='translate_arabic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='websites',
            name='translate_english',
            field=models.BooleanField(default=True),
        ),
    ]
