# Generated by Django 4.2.9 on 2025-01-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_products_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='splittedNames',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
