# Generated by Django 4.2.9 on 2025-01-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_products_splittednames'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categoryId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
